# Permalinks
permalink:           pretty

# Setup
title:               Kevin Kiningham
tagline:             Tidbits and Info
url:                 https://kkiningh.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Kevin Kiningham
  url:               https://kkiningh.github.io
  email:             kkiningh@stanford.edu

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/kkiningh/kkiningh.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
